# Advanced Array Manipulation in NumPy

In this section, we will cover advanced array manipulation techniques in NumPy. Topics include stacking, splitting, tiling, repeating, and sorting arrays.

---

### 1. Stacking Arrays

Stacking refers to joining multiple arrays along a new axis. NumPy provides several functions for this, including `np.vstack()`, `np.hstack()`, and `np.dstack()`.



In [1]:
import numpy as np

In [2]:
# Creating two arrays to stack
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Vertical stacking
vstack_result = np.vstack((arr1, arr2))
print("Vertically Stacked Arrays:\n", vstack_result)

Vertically Stacked Arrays:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
# Horizontal stacking
hstack_result = np.hstack((arr1, arr2))
print("Horizontally Stacked Arrays:\n", hstack_result)

Horizontally Stacked Arrays:
 [[1 2 5 6]
 [3 4 7 8]]


In [4]:
# Depth stacking
dstack_result = np.dstack((arr1, arr2))
print("Depth Stacked Arrays:\n", dstack_result)

Depth Stacked Arrays:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


### 2. Splitting Arrays
Splitting arrays allows you to divide an array into multiple sub-arrays. NumPy provides np.split(), np.hsplit(), and np.vsplit() to perform splitting along different axes.

In [5]:
# Splitting an array into 2 sub-arrays along axis 0
split_result = np.split(arr1, 2, axis=0)
print("Split Result:\n", split_result)

Split Result:
 [array([[1, 2]]), array([[3, 4]])]


In [6]:
# Horizontal splitting
hsplit_result = np.hsplit(arr1, 2)
print("Horizontally Split Arrays:\n", hsplit_result)

Horizontally Split Arrays:
 [array([[1],
       [3]]), array([[2],
       [4]])]


In [7]:
# Vertical splitting
vsplit_result = np.vsplit(arr1, 2)
print("Vertically Split Arrays:\n", vsplit_result)

Vertically Split Arrays:
 [array([[1, 2]]), array([[3, 4]])]


### 3. Tiling and Repeating Arrays
Tiling and repeating arrays allows us to create larger arrays by repeating the original array multiple times. NumPy provides np.tile() and np.repeat() for this purpose.

In [8]:
# Tiling the array
tiled_array = np.tile(arr1, (2, 2))
print("Tiled Array:\n", tiled_array)

Tiled Array:
 [[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


In [9]:
# Repeating elements of the array
repeated_array = np.repeat(arr1, 2, axis=1)
print("Repeated Array:\n", repeated_array)

Repeated Array:
 [[1 1 2 2]
 [3 3 4 4]]


### 4. Sorting Arrays
NumPy provides various sorting functions, such as np.sort(), np.argsort(), and np.lexsort() to sort arrays.

In [10]:
# Creating an unsorted array
unsorted_array = np.array([3, 1, 4, 1, 5, 9])

# Sorting the array
sorted_array = np.sort(unsorted_array)
print("Sorted Array:", sorted_array)

Sorted Array: [1 1 3 4 5 9]


In [11]:
# Getting the sorted indices
sorted_indices = np.argsort(unsorted_array)
print("Indices that would sort the array:", sorted_indices)

Indices that would sort the array: [1 3 0 2 4 5]


In [12]:
import numpy as np

# Two arrays for sorting: names and scores
names = np.array(['Charlie', 'Alice', 'Bob', 'Alice'])
scores = np.array([95, 85, 90, 100])

# Lexicographical sorting based on names and then scores
# Lexsort will sort by the last key (scores) first, and if scores are equal, it will sort by names.
sorted_indices = np.lexsort((scores, names))

# Using the sorted indices to sort both arrays
sorted_names = names[sorted_indices]
sorted_scores = scores[sorted_indices]

print("Sorted Indices:", sorted_indices)
print("Sorted Names:", sorted_names)
print("Sorted Scores:", sorted_scores)


Sorted Indices: [1 3 2 0]
Sorted Names: ['Alice' 'Alice' 'Bob' 'Charlie']
Sorted Scores: [ 85 100  90  95]
