# NumPy Basics

This notebook introduces the fundamental concepts of NumPy, a popular library for numerical computing in Python. We will cover topics like array creation, important attributes, initialization techniques, and random number generation.
### 1. Creating Arrays

In [18]:
import numpy as np

In [19]:
# Creating a 1D array
arr_1d = np.array([1, 2, 3])
print("1D Array:\n", arr_1d)


1D Array:
 [1 2 3]


In [20]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [21]:
# Creating a 3D array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:\n", arr_3d)


3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### 2. Array Attributes
NumPy arrays come with several important attributes, such as shape, number of dimensions, size, and data type. These attributes help us to understand the structure of the array.

In [22]:
# Checking the shape of the array
print("Shape of 1D Array:", arr_1d.shape)
print("Shape of 2D Array:", arr_2d.shape)
print("Shape of 3D Array:", arr_3d.shape)

Shape of 1D Array: (3,)
Shape of 2D Array: (2, 3)
Shape of 3D Array: (2, 2, 3)


In [23]:
# Checking the data type of the array elements
print("Data Type of 1D Array:", arr_1d.dtype)
print("Data Type of 2D Array:", arr_2d.dtype)


Data Type of 1D Array: int32
Data Type of 2D Array: int32


In [24]:
# Checking the number of dimensions
print("Number of dimensions in 1D Array:", arr_1d.ndim)
print("Number of dimensions in 2D Array:", arr_2d.ndim)
print("Number of dimensions in 3D Array:", arr_3d.ndim)

Number of dimensions in 1D Array: 1
Number of dimensions in 2D Array: 2
Number of dimensions in 3D Array: 3


In [25]:
# Checking the size (number of elements)
print("Size of 1D Array:", arr_1d.size)
print("Size of 2D Array:", arr_2d.size)
print("Size of 3D Array:", arr_3d.size)

Size of 1D Array: 3
Size of 2D Array: 6
Size of 3D Array: 12


### 3. Array Initialization Techniques
NumPy provides several methods for initializing arrays without having to manually create them from Python lists. These techniques are useful for creating arrays with zeros, ones, or random values.

In [26]:
# Creating a 2x3 array of zeros
zero_array = np.zeros((2, 3))
print("Array of Zeros:\n", zero_array)

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# Creating a 3x3 array of ones
ones_array = np.ones((3, 3))
print("Array of Ones:\n", ones_array)

Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# Creating an empty array (content will be random)
empty_array = np.empty((2, 2))
print("Empty Array (random data):\n", empty_array)

Empty Array (random data):
 [[0.25 0.5 ]
 [0.75 1.  ]]


In [29]:
# Creating a 3x3 array filled with the value 7
full_array = np.full((3, 3), 7)
print("Array filled with 7:\n", full_array)

Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [30]:
# Creating an array with values from 0 to 9
range_array = np.arange(0, 10)
print("Array with range of values:\n", range_array)

# Creating an array with 5 values evenly spaced between 0 and 1
linspace_array = np.linspace(0, 1, 5)
print("Array with evenly spaced values:\n", linspace_array)

Array with range of values:
 [0 1 2 3 4 5 6 7 8 9]
Array with evenly spaced values:
 [0.   0.25 0.5  0.75 1.  ]


In [31]:
# Creating a 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 4. Random Number Generation
NumPy has a powerful random number generation module (np.random). It provides functions to generate random numbers, including uniform and normal distributions

In [32]:
# Generating 3 random numbers between 0 and 1
rand_array = np.random.rand(3)
print("Random numbers (uniform distribution):\n", rand_array)

Random numbers (uniform distribution):
 [0.35319094 0.92621672 0.76994882]


In [33]:
# Generating 3 random numbers from a standard normal distribution
randn_array = np.random.randn(3)
print("Random numbers (normal distribution):\n", randn_array)

Random numbers (normal distribution):
 [ 2.9453942  -1.0496301  -1.08267747]


In [34]:
# Generating 5 random integers between 0 and 10
randint_array = np.random.randint(0, 10, 5)
print("Random integers:\n", randint_array)

Random integers:
 [0 9 6 4 5]
