# Advanced NumPy Features

In this section, we will explore advanced features of NumPy, including structured arrays, memory mapping, detailed broadcasting rules, conditional filtering, and multidimensional coordinate matrices.

---

### 1. Structured Arrays and Record Arrays

**Structured arrays** allow you to store data of different types in one NumPy array. Each element can have multiple fields with different types.




In [1]:
import numpy as np

In [2]:
# Defining a structured array with fields: name, age, and weight
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

# Creating the structured array
structured_array = np.array([('Alice', 25, 55.5), ('Bob', 30, 70.2)], dtype=data_type)

# Accessing individual fields
print("Names:", structured_array['name'])
print("Ages:", structured_array['age'])
print("Weights:", structured_array['weight'])

Names: ['Alice' 'Bob']
Ages: [25 30]
Weights: [55.5 70.2]


### 2. Views and Copies of Arrays
In NumPy, you can create views or copies of arrays. A view is a shallow copy (modifications affect the original), while a copy is a deep copy (completely independent of the original).

In [3]:
# Creating an array
arr = np.array([1, 2, 3, 4])

# Creating a view (shallow copy)
view_arr = arr.view()
view_arr[0] = 100
print("Original array after modifying view:", arr)

# Creating a copy (deep copy)
copy_arr = arr.copy()
copy_arr[0] = 500
print("Original array after modifying copy:", arr)

Original array after modifying view: [100   2   3   4]
Original array after modifying copy: [100   2   3   4]


### 3. Memory Mapping Files: np.memmap()
Memory mapping allows you to work with large arrays by loading only small chunks of data into memory at a time, instead of loading the entire array.

In [4]:
# Creating a memory-mapped file
memmap_array = np.memmap('files/data.memmap', dtype='float32', mode='w+', shape=(1000, 1000))

# Modifying the memory-mapped array
memmap_array[0, :] = np.arange(1000)

# Flushing changes to disk
memmap_array.flush()

# Loading the memory-mapped array
memmap_loaded = np.memmap('files/data.memmap', dtype='float32', mode='r', shape=(1000, 1000))
print("First row of the loaded memory-mapped array:", memmap_loaded[0, :10])

First row of the loaded memory-mapped array: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### 4. Broadcasting Rules in Detail
Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" smaller arrays. The dimensions must either be the same or one of them must be 1.<br>
***Broadcasting Rules***:<br>
If the two arrays differ in shape, NumPy "stretches" the smaller array along its singleton dimensions (with size 1).<br>
If dimensions do not match and neither is 1, an error is raised.

In [5]:
# Example arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([10, 20, 30])     # Shape (3,)

# Broadcasting the arrays for addition
result = arr1 + arr2
print("Broadcasting result:\n", result)

Broadcasting result:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


### 5. Using np.where() for Conditional Filtering
np.where() is used for conditional filtering and can act like an if-else statement for arrays. It returns the indices where the condition is true or provides element-wise selection.

In [6]:
# Creating an array
arr = np.array([10, 20, 30, 40, 50])

# Using np.where() to find elements greater than 25
indices = np.where(arr > 25)
print("Indices where elements are greater than 25:", indices)

# Replacing values conditionally using np.where()
result = np.where(arr > 25, arr, -1)
print("Array after conditional replacement:\n", result)

Indices where elements are greater than 25: (array([2, 3, 4], dtype=int64),)
Array after conditional replacement:
 [-1 -1 30 40 50]


### 6. Using np.meshgrid() for Multidimensional Coordinate Matrices
np.meshgrid() is used to create a grid of coordinates from two or more arrays, useful in plotting and numerical simulations.

In [7]:
# Creating two 1D arrays
x = np.array([1, 2, 3])
y = np.array([10, 20])

# Creating a 2D grid of coordinates
X, Y = np.meshgrid(x, y)

print("X grid:\n", X)
print("Y grid:\n", Y)

X grid:
 [[1 2 3]
 [1 2 3]]
Y grid:
 [[10 10 10]
 [20 20 20]]
