# Reshaping and Manipulating Arrays

In this section, we will explore how to reshape arrays, transpose them, and concatenate or split them using NumPy functions.

---

### 1. Reshaping Arrays

Reshaping allows us to change the structure of a NumPy array without changing its data. Common reshaping functions include `np.reshape()`, `np.ravel()`, and `np.flatten()`.


In [1]:
import numpy as np

In [2]:
# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to a 2x3 array
reshaped_arr = np.reshape(arr, (2, 3))
print("Reshaped Array (2x3):\n", reshaped_arr)

Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]


In [3]:
# Flattening the array using np.flatten()
flattened_arr = reshaped_arr.flatten()
print("Flattened Array (copy):", flattened_arr)

# Flattening the array using np.ravel()
raveled_arr = np.ravel(reshaped_arr)
print("Raveled Array (view):", raveled_arr)

Flattened Array (copy): [1 2 3 4 5 6]
Raveled Array (view): [1 2 3 4 5 6]


### 2. Transposing Arrays
Transposing changes the axes of an array. You can use np.transpose() or np.swapaxes() to perform this operation.

In [4]:
# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

# Transposing the matrix
transposed_matrix = np.transpose(matrix)
print("Transposed Matrix:\n", transposed_matrix)

Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]


In [5]:
# Creating a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])

# Swapping axes 0 and 2
swapped_axes_arr = np.swapaxes(arr_3d, 0, 2)
print("Array with Swapped Axes (0 and 2):\n", swapped_axes_arr)

Array with Swapped Axes (0 and 2):
 [[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


### 3. Concatenation and Splitting Arrays
NumPy provides functions to concatenate arrays along various axes and split them into smaller arrays.

In [6]:
# Creating two arrays to concatenate
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenating along axis 0 (vertically)
concat_arr = np.concatenate((arr1, arr2), axis=0)
print("Concatenated Array (along axis 0):\n", concat_arr)

# Horizontal stacking
hstack_arr = np.hstack((arr1, arr2))
print("Horizontally Stacked Array:\n", hstack_arr)

# Vertical stacking
vstack_arr = np.vstack((arr1, arr2))
print("Vertically Stacked Array:\n", vstack_arr)


Concatenated Array (along axis 0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally Stacked Array:
 [[1 2 5 6]
 [3 4 7 8]]
Vertically Stacked Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
# Creating an array to split
arr_to_split = np.array([[1, 2, 3, 4], 
                         [5, 6, 7, 8]])

# Splitting into 2 sub-arrays along axis 1 (columns)
split_arr = np.split(arr_to_split, 2, axis=1)
print("Split Array (into 2 sub-arrays along axis 1):", split_arr)

# Horizontally splitting the array into 2
hsplit_arr = np.hsplit(arr_to_split, 2)
print("Horizontally Split Array:", hsplit_arr)

# Vertically splitting the array into 2
vsplit_arr = np.vsplit(arr_to_split, 2)
print("Vertically Split Array:", vsplit_arr)


Split Array (into 2 sub-arrays along axis 1): [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
Horizontally Split Array: [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
Vertically Split Array: [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
