# Array I/O (Input/Output) in NumPy

NumPy provides multiple ways to save and load arrays to and from files. This section covers saving to and loading from text files, working with binary files, and handling CSV files.

---

### 1. Saving and Loading Data

In [1]:
import numpy as np

## Creating a Folder and Uploading a File in Google Colab

In this tutorial, we'll go through the steps to create a folder and upload a file to that folder in Google Colab.

### 1. Create a Folder

First, we'll create a folder named `data` using Python's `os.makedirs` function.
### 2 .Upload your data into colab new created folder

In [2]:
# For colab to create a folder named 'files'
import os
os.makedirs('data', exist_ok=True)

In [3]:
# Creating a 2D array
arr = np.array([[1.5, 2.7, 3.1], [4.3, 5.9, 6.8]])

# Saving the array to a text file
np.savetxt("data/array_data.txt", arr, delimiter=',', fmt='%.2f')

In [4]:
# Loading the array from the text file
loaded_arr = np.loadtxt("data/array_data.txt", delimiter=',')
print("Array loaded from 'data/array_data.txt':\n", loaded_arr)

Array loaded from 'data/array_data.txt':
 [[1.5 2.7 3.1]
 [4.3 5.9 6.8]]


### 2. Working with Binary Data Files
B3inary formats are more efficient for large datasets as they avoid the overhead of converting data to and from text.

In [5]:
# Saving the array to a binary file
np.save("data/array_data.npy", arr)
print("Array saved to 'data/array_data.npy'")

Array saved to 'data/array_data.npy'


In [6]:
# Loading the array from the binary file
loaded_binary_arr = np.load("data/array_data.npy")
print("Array loaded from 'data/array_data.npy':\n", loaded_binary_arr)

Array loaded from 'data/array_data.npy':
 [[1.5 2.7 3.1]
 [4.3 5.9 6.8]]


In [7]:
# Creating two more arrays
arr2 = np.array([10, 20, 30, 40])
arr3 = np.array([[7, 8], [9, 10]])

# Saving multiple arrays to a .npz file
np.savez("data/multiple_arrays.npz", array1=arr, array2=arr2, array3=arr3)
print("Multiple arrays saved to 'data/multiple_arrays.npz'")

Multiple arrays saved to 'data/multiple_arrays.npz'


In [8]:
# Loading multiple arrays from the .npz file
loaded = np.load("data/multiple_arrays.npz")
print("Loaded array1:\n", loaded['array1'])
print("Loaded array2:\n", loaded['array2'])
print("Loaded array3:\n", loaded['array3'])

Loaded array1:
 [[1.5 2.7 3.1]
 [4.3 5.9 6.8]]
Loaded array2:
 [10 20 30 40]
Loaded array3:
 [[ 7  8]
 [ 9 10]]


### 3. Working with CSV Files
CSV files (Comma Separated Values) are a common format for storing tabular data.

In [9]:
# Loading data from a CSV file
csv_data = np.genfromtxt("data/data.csv", delimiter=',', skip_header=1)
print("Data loaded from 'data.csv':\n", csv_data)

Data loaded from 'data.csv':
 [[ 5.  20. ]
 [ 6.  37. ]
 [ 5.8 25. ]]


In [10]:
# Loading data from a CSV file into a record array
record_data = np.recfromcsv("data/data.csv", delimiter=',', encoding='utf-8', case_sensitive=True)
print("Data loaded into record array from 'data/data.csv':")
print("First column:", record_data[0])

Data loaded into record array from 'data/data.csv':
First column: (5., 20)
