# Array Operations in NumPy

This section covers various operations that can be performed on NumPy arrays. We will look at element-wise arithmetic, broadcasting, universal functions, comparison operators, aggregation functions, and matrix operations like the dot product.

---

### 1. Arithmetic Operations on Arrays

NumPy supports element-wise arithmetic operations such as addition, subtraction, multiplication, and division. When performing these operations, the shape of the arrays must match or broadcasting rules must apply.

In [1]:
import numpy as np

In [2]:


# Creating two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Element-wise addition
add_result = arr1 + arr2
print("Addition result:", add_result)

# Element-wise subtraction
sub_result = arr1 - arr2
print("Subtraction result:", sub_result)

# Element-wise multiplication
mul_result = arr1 * arr2
print("Multiplication result:", mul_result)

# Element-wise division
div_result = arr1 / arr2
print("Division result:", div_result)


Addition result: [ 6  8 10 12]
Subtraction result: [-4 -4 -4 -4]
Multiplication result: [ 5 12 21 32]
Division result: [0.2        0.33333333 0.42857143 0.5       ]


In [3]:
# Broadcasting example: adding a scalar to an array
arr = np.array([1, 2, 3, 4])
scalar = 10

broadcast_result = arr + scalar
print("Broadcasting result:", broadcast_result)

Broadcasting result: [11 12 13 14]


In [4]:
# Using universal functions for element-wise operations
add_ufunc = np.add(arr1, arr2)
sub_ufunc = np.subtract(arr1, arr2)
mul_ufunc = np.multiply(arr1, arr2)
div_ufunc = np.divide(arr1, arr2)

print("Addition with ufunc:", add_ufunc)
print("Subtraction with ufunc:", sub_ufunc)
print("Multiplication with ufunc:", mul_ufunc)
print("Division with ufunc:", div_ufunc)

Addition with ufunc: [ 6  8 10 12]
Subtraction with ufunc: [-4 -4 -4 -4]
Multiplication with ufunc: [ 5 12 21 32]
Division with ufunc: [0.2        0.33333333 0.42857143 0.5       ]


### 2. Comparison Operators
NumPy arrays support comparison operators like >, <, ==, !=. These operations return boolean arrays that show the result of the comparison for each element.

In [5]:
# Comparison between arrays
greater_than = arr1 > arr2
print("arr1 > arr2:", greater_than)

# Equality check
equal_check = arr1 == arr2
print("arr1 == arr2:", equal_check)

# Not Equality check
equal_check = arr1 != arr2
print("arr1 != arr2:", equal_check)

arr1 > arr2: [False False False False]
arr1 == arr2: [False False False False]
arr1 != arr2: [ True  True  True  True]


### 3. Aggregation Functions
NumPy provides functions to perform aggregations on arrays, such as sum, mean, min, max, standard deviation, and more.

In [6]:
# Creating a sample array
arr = np.array([1, 2, 3, 4, 5])

# Sum of all elements
sum_result = np.sum(arr)
print("Sum:", sum_result)

# Mean (average) of all elements
mean_result = np.mean(arr)
print("Mean:", mean_result)

# Minimum and maximum value
min_result = np.min(arr)
max_result = np.max(arr)
print("Min:", min_result)
print("Max:", max_result)

# Standard deviation
std_result = np.std(arr)
print("Standard Deviation:", std_result)

Sum: 15
Mean: 3.0
Min: 1
Max: 5
Standard Deviation: 1.4142135623730951


### 4. Dot Product and Matrix Multiplication
NumPy provides several ways to compute the dot product or perform matrix multiplication on arrays.



In [7]:
# Creating two arrays for dot product
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Dot product of two 1D arrays
dot_product = np.dot(arr1, arr2)
print("Dot product (1D arrays):", dot_product)

Dot product (1D arrays): 32


In [8]:
# Creating two 2D arrays (matrices)
matrix1 = np.array([[1, 2],
                    [3, 4]])
matrix2 = np.array([[5, 6],
                    [7, 8]])

# Matrix multiplication using @ operator
matrix_mul_1 = matrix1 @ matrix2
print("Matrix multiplication using @ operator:\n", matrix_mul_1)

# Matrix multiplication using np.matmul()
matrix_mul_2 = np.matmul(matrix1, matrix2)
print("Matrix multiplication using np.matmul():\n", matrix_mul_2)


Matrix multiplication using @ operator:
 [[19 22]
 [43 50]]
Matrix multiplication using np.matmul():
 [[19 22]
 [43 50]]


### Difference in dot product and element-wise multiplication

In [9]:
import numpy as np

# Creating two 2D arrays (matrices)
matrix1 = np.array([[1, 2], 
                    [3, 4]])
matrix2 = np.array([[5, 6], 
                    [7, 8]])

# Element-wise multiplication
elementwise_mul = matrix1 * matrix2
print("Element-wise Multiplication:\n", elementwise_mul)

# Dot product (matrix multiplication)
dot_product = np.dot(matrix1, matrix2)
print("\nDot Product (Matrix Multiplication):\n", dot_product)


Element-wise Multiplication:
 [[ 5 12]
 [21 32]]

Dot Product (Matrix Multiplication):
 [[19 22]
 [43 50]]
