# Array Indexing and Slicing

In this section, we will learn how to access and modify elements in NumPy arrays. We will cover basic array indexing, slicing, fancy indexing, and modifying array elements using indexing.

---

### 1. Accessing Array Elements



In [1]:
import numpy as np

In [2]:
# Creating a 1D array
arr = np.array([10, 20, 30, 40, 50])

# Creating a 2D array (matrix)
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Accessing the first element
print("First element:", arr[0])

# Accessing the third element
print("Third element:", arr[2])

# Accessing the element at row 1, column 2 (remember, indices start from 0)
print("Element at row 1, column 2:", arr_2d[1, 2])

First element: 10
Third element: 30
Element at row 1, column 2: 60


### 2. Slicing Arrays
Slicing allows us to access a range of elements in an array. The syntax for slicing is array <span style="background-color:green">***[start:stop:step]***</span>, where start is the index to start at, stop is the index to stop before, and step is the interval between elements

In [3]:
# Slicing from index 1 to 4
print("Elements from index 1 to 4:", arr[1:5])

# Slicing from index 2 to the end
print("Elements from index 2 to end:", arr[2:])

# Slicing every second element
print("Every second element:", arr[::2])

# Reversing the array using slicing
print("Reversed array:", arr[::-1])

# Slicing the last 4 numbers and reversing them
reversed_last_4 = arr[-4:][::-1]
print("Reversed last 4 numbers:", reversed_last_4)

Elements from index 1 to 4: [20 30 40 50]
Elements from index 2 to end: [30 40 50]
Every second element: [10 30 50]
Reversed array: [50 40 30 20 10]
Reversed last 4 numbers: [50 40 30 20]


##### 2D Array Slicing

In [4]:
# Slicing the 2D array second row (row at index 1)
print("Second row:", arr_2d[1, :])


# Slicing the 2D array third column (column at index 2)
print("Third column:", arr_2d[:, 2])

# Slicing a 2d array subarray: rows 0 to 1, columns 1 to 2
print("Sliced subarray (rows 0 to 1, columns 1 to 2):\n", arr_2d[0:2, 1:3])


# Reversing the order of rows
print("Array with reversed rows:\n", arr_2d[::-1, :])

# Reversing the order of columns
print("Array with reversed columns:\n", arr_2d[:, ::-1])

# Reversing both rows and columns
print("Array with both rows and columns reversed:\n", arr_2d[::-1, ::-1])




Second row: [40 50 60]
Third column: [30 60 90]
Sliced subarray (rows 0 to 1, columns 1 to 2):
 [[20 30]
 [50 60]]
Array with reversed rows:
 [[70 80 90]
 [40 50 60]
 [10 20 30]]
Array with reversed columns:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]
Array with both rows and columns reversed:
 [[90 80 70]
 [60 50 40]
 [30 20 10]]


### 3. Fancy Indexing
Fancy indexing allows us to select specific elements from an array using integer or boolean arrays. It is a powerful way to index multiple elements at once

In [5]:
# Creating a new 1D array
arr = np.array([10, 20, 30, 40, 50, 60])

# Accessing elements at index 1, 3, and 5
indices = [1, 3, 5]
print("Elements at indices 1, 3, and 5:", arr[indices])

Elements at indices 1, 3, and 5: [20 40 60]


In [6]:
# Creating a boolean array where elements greater than 30 are selected
bool_array = arr > 30
print("Elements greater than 30:", arr[bool_array])

# Another example: selecting even elements
even_elements = arr % 2 == 0
print("Even elements:", arr[even_elements])

Elements greater than 30: [40 50 60]
Even elements: [10 20 30 40 50 60]


### 4. Modifying Array Elements with Indexing
We can modify elements in a NumPy array by using indexing. This allows us to change specific elements or a range of elements.

In [7]:
# Modifying the element at index 2
arr[2] = 100
print("Modified array (index 2 changed to 100):", arr)

# Modifying multiple elements using slicing
arr[1:4] = [200, 300, 400]
print("Modified array (indices 1 to 3 changed):", arr)

# Modifying multiple elements using slicing with a single value
arr[1:4] = 200
print("Modified array (indices 1 to 3 changed) with single value:", arr)

Modified array (index 2 changed to 100): [ 10  20 100  40  50  60]
Modified array (indices 1 to 3 changed): [ 10 200 300 400  50  60]
Modified array (indices 1 to 3 changed) with single value: [ 10 200 200 200  50  60]


##### 2D Array Modifying

In [8]:
# Modifying the entire second row
arr_2d[1, :] = [400, 500, 600]
print("Modified 2D Array (second row changed):\n", arr_2d)

# Modifying the third column
arr_2d[:, 2] = [300, 600, 900]
print("Modified 2D Array (third column changed):\n", arr_2d)

# Modifying a subarray (rows 0 to 1, columns 1 to 2)
arr_2d[0:2, 1:3] = [[200, 300], [500, 600]]
print("Modified 2D Array (subarray changed):\n", arr_2d)


Modified 2D Array (second row changed):
 [[ 10  20  30]
 [400 500 600]
 [ 70  80  90]]
Modified 2D Array (third column changed):
 [[ 10  20 300]
 [400 500 600]
 [ 70  80 900]]
Modified 2D Array (subarray changed):
 [[ 10 200 300]
 [400 500 600]
 [ 70  80 900]]
