# NumPy and Linear Algebra

NumPy provides powerful linear algebra functions through the `np.linalg` module. These functions allow us to compute matrix properties and perform operations like finding determinants, matrix inversion, solving linear equations, eigenvalue decomposition, and singular value decomposition.

---

### 1. Basics of Linear Algebra in NumPy

Let's explore the basics of linear algebra operations using NumPy, including matrix determinants, matrix inversions, solving linear equations, and eigenvalues/eigenvectors.




In [1]:
import numpy as np

In [2]:


# Creating a 2x2 matrix
matrix = np.array([[4, 7], 
                   [2, 6]])

# Calculating the determinant
det = np.linalg.det(matrix)
print("Determinant of the matrix:", det)

Determinant of the matrix: 10.000000000000002


In [3]:
# Calculating the inverse of the matrix
inverse_matrix = np.linalg.inv(matrix)
print("Inverse of the matrix:\n", inverse_matrix)

# Verifying by multiplying the matrix with its inverse
identity_matrix = np.dot(matrix, inverse_matrix)
print("Matrix multiplied by its inverse (Identity Matrix):\n", identity_matrix)

Inverse of the matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Matrix multiplied by its inverse (Identity Matrix):
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [4]:
# Coefficient matrix (A)
A = np.array([[3, 1], 
              [1, 2]])

# Constants matrix (b)
b = np.array([9, 8])

# Solving for x
x = np.linalg.solve(A, b)
print("Solution for the system of linear equations (x):", x)

Solution for the system of linear equations (x): [2. 3.]


In [5]:
# Calculating eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [1.12701665 8.87298335]
Eigenvectors:
 [[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]


### 2. Singular Value Decomposition (SVD): np.linalg.svd()
Singular Value Decomposition (SVD) is a factorization of a matrix A=UΣV<sup>t</sup> where 𝑈,Σ, and V are matrices. SVD is widely used in applications like dimensionality reduction and signal processing.
 

In [6]:
# Creating a matrix for SVD
matrix_svd = np.array([[1, 2], 
                       [3, 4], 
                       [5, 6]])

# Performing Singular Value Decomposition
U, S, Vt = np.linalg.svd(matrix_svd)

print("U matrix:\n", U)
print("Singular values (Sigma):", S)
print("V transpose matrix (V^T):\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular values (Sigma): [9.52551809 0.51430058]
V transpose matrix (V^T):
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
